
language: node_js
sudo: false
dist: trusty
node_js:
  - "9"

services:
  - docker

cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn

script:
  - yarn build
  - docker build -t openpitrix/docs.openpitrix.io .
